-- AlterEnum
ALTER TYPE "Role" ADD VALUE 'SUPER_ADMIN';
ALTER TYPE "Role" ADD VALUE 'OPS_MANAGER';
ALTER TYPE "Role" ADD VALUE 'ACCOUNT_EXEC';
ALTER TYPE "Role" ADD VALUE 'CARRIER_RELATIONS';
ALTER TYPE "Role" ADD VALUE 'SUPPORT';
ALTER TYPE "Role" ADD VALUE 'AUDITOR';
ALTER TYPE "Role" ADD VALUE 'CARRIER';
